apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-music1
  description: api-music1 API
  annotations:
    argocd/app-name: api-imdb
    # grafana/overview-dashboard: "https://grafana.jppol.click/goto/Hw7n7PzHR?orgId=1"
    # grafana/dashboard-selector: nginx
    backstage.io/kubernetes-namespace: "api-music1"
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/name=api-music1'
    #prometheus.io/rule: sum by (ingress) (nginx_ingress_controller_requests{ingress!=""}), nginx_ingress_controller_nginx_process_resident_memory_bytes
    kubecost.com/deployment-name: "api-music1"
  links:
    - url: https://api-imdb.jppol.click/docs
      title: Documentation
      icon: documentation
    - url: https://grafana.jppol.click/goto/JCdVqlzHg?orgId=1
      title: Grafana loki Access log explorer
      icon: grafana
spec:
  type: openapi
  owner: idp-admins
  lifecycle: experimental
  definition:
    $text: https://api-music1.jppol.click/openapi.json
